# This is a basic workflow to help you get started with Actions

name: Test -3 branch  work flow

# on:
#   push:
#     branches: [ test_runner ]
#   pull_request:
#     branches: [ test_runner ]

on:
 workflow_dispatch:
    inputs:
      namr:
        description: 'namr of the emp'     
        required: true
        default: 'test'
      class:
        type: choice
        description: Select stage
        options:
        - TEST
        - INT
        - PROD
      version:
        description: 'service version'     
        required: true
        default: '0.0.1-1'
      suffix:
        description: 'suffix version'     
        required: true
        default: 'CHANGEME'
      emptysuffix:
        type: boolean
        description: Empty Suffix 
    
    
jobs:
  build:
    runs-on: [ 'Linux' ]
    steps:
    - uses: AutoModality/action-clean@v1
    - uses: rtCamp/action-cleanup@master
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'adopt'
          overwrite-settings: false
    - run: |
              echo "$JAVA_HOME"
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.2         
    - name: Build & Deploy Artifact 
      run: mvn deploy -DaltDeploymentRepository=ntg7-onsiteassistant::default::https://jfrogedc.gsep.daimler.com/artifactory/ntg7-onsiteassistant/ --no-transfer-progress -e -V -f pom.xml -Dmaven.wagon.http.retryHandler.nonRetryableClasses=java.io.InterruptedIOException,java.net.UnknownHostException,javax.net.ssl.SSLException -Dstyle.color=always
